<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-9SDI6F6U" name="Cucumber Tests" tests="2" failures="1" timestamp="6 Jun 2019 15:52:57 GMT" time="67.548" errors="0">
  <testcase name="feature" time="41.728" classname="runner.MainRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [thankyouforyourmessage!] but found [thankyouforyourmessage!6]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [thankyouforyourmessage!] but found [thankyouforyourmessage!6]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: expected [thankyouforyourmessage!] but found [thankyouforyourmessage!6]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at pageObjects.ContactUs_Page.confirmContactUsFormSubmissionWasSuccessful(ContactUs_Page.java:63)
	at steps.ContactUsSteps.the_information_should_successfully_be_submitted_via_the_contact_us_form(ContactUsSteps.java:44)
	at âœ½.Then The information should successfully be submitted via the contact us form(ContactUs.feature:12)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="22.247" classname="runner.MainRunner"/>
</testsuite> <!-- Cucumber Tests -->
